### ISSUE TITLE
scx30g_v2: Codecs don't work

### ISSUE THREAD

**Issue by koquantam** [koquantam/android_hardware_sprd#5]
The recorded videos are just like the TV when it's out-of-signal

**Comment by ngoquang2708** [comment]
Any logcat?

**Comment by koquantam** [comment]
@ngoquang2708 
Bro, please take a look at this
![screenshot from 2016-08-12 20 22 58](https://cloud.githubusercontent.com/assets/13411810/17623800/15ca499e-60cc-11e6-9105-ed8a9f51f5ba.png)

**Comment by koquantam** [comment]
IDK why header file and C file functions are match, but get conflicts

**Comment by ngoquang2708** [comment]
Try ```mm -B```.

**Comment by koquantam** [comment]
OK thanks, I solved it
There was some conflicts with ion.h of kernel source

**Comment by koquantam** [comment]
Somehow I got SIGBUS error and BUS_ADRALN. Here's the logcat
`08-17 15:26:20.821  2808  2991 I SprdOMXPlugin: makeComponentInstance 'OMX.sprd.mpeg4.decoder'
08-17 15:26:20.825  2808  2991 I SPRDMPEG4Decoder: Construct SPRDMPEG4Decoder, this: b60f4e00
08-17 15:26:20.825  2808  2991 I SPRDMPEG4Decoder: openDecoder, lib: libomx_m4vh263dec_sw_sprd.so
08-17 15:26:20.826  2808  2991 E SPRDMPEG4Decoder: openDecoder, can't open lib: libomx_m4vh263dec_sw_sprd.so
08-17 15:26:20.826  2808  2991 I SPRDMPEG4Decoder: openDecoder, lib: libomx_m4vh263dec_hw_sprd.so
08-17 15:26:20.829  2808  2991 I SPRDMPEG4Decoder: SPRDMPEG4Decoder, is IOMMU enabled: 1
08-17 15:26:20.832  2808  2991 F libc    : Fatal signal 7 (SIGBUS), code 1, fault addr 0x3 in tid 2991 (Binder_2)
08-17 15:26:20.833   249   249 I DEBUG   : property debug.db.uid not set; NOT waiting for gdb.
08-17 15:26:20.833   249   249 I DEBUG   : HINT: adb shell setprop debug.db.uid 100000
08-17 15:26:20.833   249   249 I DEBUG   : HINT: adb forward tcp:5039 tcp:5039
08-17 15:26:20.936   249   249 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
08-17 15:26:20.937  1953  2628 W NativeCrashListener: Couldn't find ProcessRecord for pid 2808
08-17 15:26:20.937   249   249 F DEBUG   : CM Version: '13.0-20160817-UNOFFICIAL-grandprimeve3g'
08-17 15:26:20.937   249   249 E DEBUG   : AM write failed: Broken pipe
08-17 15:26:20.937   249   249 F DEBUG   : Build fingerprint: 'samsung/cm_grandprimeve3g/grandprimeve3g:6.0.1/MOB30R/30cad0f1e7:userdebug/test-keys'
08-17 15:26:20.937   249   249 F DEBUG   : Revision: '0'
08-17 15:26:20.937   249   249 F DEBUG   : ABI: 'arm'
08-17 15:26:20.938   249   249 F DEBUG   : pid: 2808, tid: 2991, name: Binder_2  >>> /system/bin/mediaserver <<<
08-17 15:26:20.939   249   249 F DEBUG   : signal 7 (SIGBUS), code 1 (BUS_ADRALN), fault addr 0x3
08-17 15:26:20.952  1953  1953 E NetdConnector: NDC Command {3 strict enable} took too long (2564ms)
08-17 15:26:20.953  1953  2571 E NetdConnector: NDC Command {4 interface getcfg wlan0} took too long (2564ms)
08-17 15:26:20.955  1660  2542 D CommandListener: Setting iface cfg
08-17 15:26:20.955  1660  2542 D CommandListener: Trying to bring down wlan0
08-17 15:26:20.959  1660  2542 D CommandListener: Clearing all IP addresses on wlan0
08-17 15:26:20.981  1953  1953 W System  : ClassLoader referenced unknown path: /system/framework/ConnectivityExt.jar
08-17 15:26:20.982  1953  1953 W ConnectivityExtension: Connectivity extension is not available
08-17 15:26:20.997   249   249 F DEBUG   :     r0 00000003  r1 b60f4e8c  r2 00000001  r3 b1e3fe90
08-17 15:26:20.997   249   249 F DEBUG   :     r4 ffffffff  r5 b1ddc780  r6 000039c4  r7 00000000
08-17 15:26:20.998   249   249 F DEBUG   :     r8 00000001  r9 00000001  sl b608ae40  fp b1c80344
08-17 15:26:20.998   249   249 F DEBUG   :     ip b6bf3c24  sp af12e568  lr b6be861d  pc b6be8602  cpsr 200f0030
08-17 15:26:21.014   249   249 F DEBUG   : 
08-17 15:26:21.014   249   249 F DEBUG   : backtrace:
08-17 15:26:21.014   249   249 F DEBUG   :     #00 pc 0000e602  /system/lib/libutils.so (_ZN7android7RefBase12weakref_type7incWeakEPKv+5)
08-17 15:26:21.014   249   249 F DEBUG   :     #01 pc 0000e619  /system/lib/libutils.so (_ZNK7android7RefBase9incStrongEPKv+6)
08-17 15:26:21.014   249   249 F DEBUG   :     #02 pc 00006244  /system/lib/libstagefright_sprd_mpeg4dec.so (_ZN7android2spINS_13MemoryHeapIonEEaSEPS1_+32)
08-17 15:26:21.014   249   249 F DEBUG   :     #03 pc 00006314  /system/lib/libstagefright_sprd_mpeg4dec.so (_ZN7android16SPRDMPEG4Decoder11initDecoderEv+160)
08-17 15:26:21.015   249   249 F DEBUG   :     #04 pc 00006760  /system/lib/libstagefright_sprd_mpeg4dec.so (_ZN7android16SPRDMPEG4DecoderC2EPKcPK16OMX_CALLBACKTYPEPvPP17OMX_COMPONENTTYPE+528)
08-17 15:26:21.015   249   249 F DEBUG   :     #05 pc 00006afc  /system/lib/libstagefright_sprd_mpeg4dec.so (_Z22createSprdOMXComponentPKcPK16OMX_CALLBACKTYPEPvPP17OMX_COMPONENTTYPE+52)
08-17 15:26:21.015   249   249 F DEBUG   :     #06 pc 00004b97  /system/lib/libstagefrighthw.so (_ZN7android13SprdOMXPlugin21makeComponentInstanceEPKcPK16OMX_CALLBACKTYPEPvPP17OMX_COMPONENTTYPE+170)
08-17 15:26:21.015   249   249 F DEBUG   :     #07 pc 0001911b  /system/lib/libstagefright_omx.so (_ZN7android9OMXMaster21makeComponentInstanceEPKcPK16OMX_CALLBACKTYPEPvPP17OMX_COMPONENTTYPE+106)
08-17 15:26:21.015   249   249 F DEBUG   :     #08 pc 0001766d  /system/lib/libstagefright_omx.so (_ZN7android3OMX12allocateNodeEPKcRKNS_2spINS_12IOMXObserverEEEPj+76)
08-17 15:26:21.015   249   249 F DEBUG   :     #09 pc 00088ce7  /system/lib/libmedia.so (_ZN7android5BnOMX10onTransactEjRKNS_6ParcelEPS1_j+582)
08-17 15:26:21.016   249   249 F DEBUG   :     #10 pc 000199d9  /system/lib/libbinder.so (_ZN7android7BBinder8transactEjRKNS_6ParcelEPS1_j+60)
08-17 15:26:21.016   249   249 F DEBUG   :     #11 pc 0001ece5  /system/lib/libbinder.so (_ZN7android14IPCThreadState14executeCommandEi+532)
08-17 15:26:21.017   249   249 F DEBUG   :     #12 pc 0001ee51  /system/lib/libbinder.so (_ZN7android14IPCThreadState20getAndExecuteCommandEv+64)
08-17 15:26:21.017   249   249 F DEBUG   :     #13 pc 0001eeb5  /system/lib/libbinder.so (_ZN7android14IPCThreadState14joinThreadPoolEb+48)
08-17 15:26:21.017   249   249 F DEBUG   :     #14 pc 0002389d  /system/lib/libbinder.so
08-17 15:26:21.017   249   249 F DEBUG   :     #15 pc 00010121  /system/lib/libutils.so (_ZN7android6Thread11_threadLoopEPv+112)
08-17 15:26:21.017   249   249 F DEBUG   :     #16 pc 0003fa2b  /system/lib/libc.so (_ZL15__pthread_startPv+30)
08-17 15:26:21.018   249   249 F DEBUG   :     #17 pc 0001a065  /system/lib/libc.so (__start_thread+6)
08-17 15:26:21.064  2071  2071 D gralloc.sc8830: fb_post fps = 27.995729
08-17 15:26:21.066  1953  2581 E AudioService: Media server died.`

**Comment by koquantam** [comment]
What I do is shimming stock and our libmemoryheapion

**Comment by ngoquang2708** [comment]
Why don't you just use your stock ```libmemoryheapion``?

**Comment by koquantam** [comment]
This is what I get if I use stock libmemoryheapion
`08-16 14:23:44.818   303  1382 E OMX     : FAILED to allocate omx component 'OMX.sprd.h263.decoder' err=InvalidComponentName(0x80001002)`

**Comment by ngoquang2708** [comment]
OK, so it works. You should use all of its codecs related stuffs includes ```libstagefright_sprd_*.so```, ```libomx_*.so``` and ```libstagefrighthw.so```.

**Comment by ngoquang2708** [comment]
Plus your stock ```media_codecs.xml```.

**Comment by koquantam** [comment]
Bad news for us: git.mozilla.org has been decomissed

**Comment by koquantam** [comment]
Spreadtrum is now officially closed-source. Now the hopes left come from us

**Comment by ngoquang2708** [comment]
If I would buy any smartphone in the future, I will chose QCOM hardware.

**Comment by koquantam** [comment]
Yes and me Exynos
